[[hardware]]
id = "mini"
label = "Atem Mini"
address = "192.168.2.84"

[[frontend]]
type = "http-api"
bind = ":8080"
auth = false
hardware = "mini"

[[frontend]]
type = "websocket"
bind = ":8081"
auth = true
username = "admin"
password = "admin"
hardware = "mini"
static-files = "/var/www/mywebapp"

[[frontend]]
type = "status"
bind = "127.0.0.1:8082"
auth = false

[[frontend]]
type = "tcp"
bind = ":8083"
auth = true
username = "admin"
password = "password"
hardware = "mini"

[[frontend]]
type = "mqtt"
host = "localhost:1883"
hardware = "mini"
auth = false
allow-writes = false

[[frontend]]
type = "midi"
bind = "any"

"*/NOTE-ON/64" = { hardware = "mini", field = "program-input", index = 0, source = 1 }
"*/NOTE-ON/65" = { hardware = "mini", field = "program-input", index = 0, source = 2 }
"*/NOTE-ON/66" = { hardware = "mini", field = "program-input", index = 0, source = 3 }
"*/NOTE-ON/67" = { hardware = "mini", field = "program-input", index = 0, source = 4 }
"*/NOTE-ON/32" = { hardware = "mini", field = "preview-input", index = 0, source = 1 }
"*/NOTE-ON/33" = { hardware = "mini", field = "preview-input", index = 0, source = 2 }
"*/NOTE-ON/34" = { hardware = "mini", field = "preview-input", index = 0, source = 3 }
"*/NOTE-ON/35" = { hardware = "mini", field = "preview-input", index = 0, source = 4 }