[[hardware]]
id = "mini"
label = "Atem Mini"
address = "192.168.2.84"

[[hardware]]
id = "mini2"
label = "Testdevice"
address = "192.168.2.17"

[[hardware]]
id = "merged"
label = "Mini 2M/E"
hardware = "mini,mini2"
type = "merge-me"
me-input = 4

[[frontend]]
type = "http-api"
bind = ":8080"
auth = false
hardware = "mini,mini2,merged"

[[frontend]]
type = "websocket"
bind = ":8081"
auth = true
username = "admin"
password = "admin"
hardware = "mini,mini2"
static-files = "/var/www/mywebapp"

[[frontend]]
type = "status"
bind = "127.0.0.1:8082"
auth = false

[[frontend]]
type = "tcp"
bind = ":8083"
auth = true
username = "admin"
password = "password"
hardware = "mini,mini2"