[[hardware]]
id = "mini"
label = "Atem Mini"
address = "192.168.2.52"

[[frontend]]
type = "status"
bind = "127.0.0.1:8082"
auth = false

[[frontend]]
type = "midi"
bind = "any"
auth = false
dump = true

"*/NOTE-ON/50/127" = { hardware = "mini", field = "auto", index = 0 }

"*/NOTE-ON/24/127" = { hardware = "mini", field = "preview-input", index = 0, source = 1 }
"*/NOTE-ON/25/127" = { hardware = "mini", field = "preview-input", index = 0, source = 2 }
"*/NOTE-ON/26/127" = { hardware = "mini", field = "preview-input", index = 0, source = 3 }
"*/NOTE-ON/27/127" = { hardware = "mini", field = "preview-input", index = 0, source = 4 }
"*/NOTE-ON/28/127" = { hardware = "mini", field = "preview-input", index = 0, source = 5 }
"*/NOTE-ON/29/127" = { hardware = "mini", field = "preview-input", index = 0, source = 6 }
"*/NOTE-ON/30/127" = { hardware = "mini", field = "preview-input", index = 0, source = 7 }
"*/NOTE-ON/31/127" = { hardware = "mini", field = "preview-input", index = 0, source = 8 }

"*/NOTE-ON/0/127" = { hardware = "mini", field = "program-input", index = 0, source = 1 }
"*/NOTE-ON/1/127" = { hardware = "mini", field = "program-input", index = 0, source = 2 }
"*/NOTE-ON/2/127" = { hardware = "mini", field = "program-input", index = 0, source = 3 }
"*/NOTE-ON/3/127" = { hardware = "mini", field = "program-input", index = 0, source = 4 }
"*/NOTE-ON/4/127" = { hardware = "mini", field = "program-input", index = 0, source = 5 }
"*/NOTE-ON/5/127" = { hardware = "mini", field = "program-input", index = 0, source = 6 }
"*/NOTE-ON/6/127" = { hardware = "mini", field = "program-input", index = 0, source = 7 }
"*/NOTE-ON/7/127" = { hardware = "mini", field = "program-input", index = 0, source = 8 }

"8/PITCH-BEND" = { hardware = "mini", field = "transition-position", index = 0, position = "$value"}

"mini:preview-bus-input:index=0:source=1" = "0/NOTE-ON/24/127"
"mini:preview-bus-input:index=0:source=2" = "0/NOTE-ON/25/127"
"mini:preview-bus-input:index=0:source=3" = "0/NOTE-ON/26/127"
"mini:preview-bus-input:index=0:source=4" = "0/NOTE-ON/27/127"
"mini:preview-bus-input:index=0:source=5" = "0/NOTE-ON/28/127"
"mini:preview-bus-input:index=0:source=6" = "0/NOTE-ON/29/127"
"mini:preview-bus-input:index=0:source=7" = "0/NOTE-ON/30/127"
"mini:preview-bus-input:index=0:source=8" = "0/NOTE-ON/31/127"

"mini:program-bus-input:index=0:source=1" = "0/NOTE-ON/0/127"
"mini:program-bus-input:index=0:source=2" = "0/NOTE-ON/1/127"
"mini:program-bus-input:index=0:source=3" = "0/NOTE-ON/2/127"
"mini:program-bus-input:index=0:source=4" = "0/NOTE-ON/3/127"
"mini:program-bus-input:index=0:source=5" = "0/NOTE-ON/4/127"
"mini:program-bus-input:index=0:source=6" = "0/NOTE-ON/5/127"
"mini:program-bus-input:index=0:source=7" = "0/NOTE-ON/6/127"
"mini:program-bus-input:index=0:source=8" = "0/NOTE-ON/7/127"

"mini:transition-position:index=0:position" = "8/PITCH-BEND/9"
"mini:transition-position:index=0:in_transition=1" = "0/NOTE-ON/50/127"