image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
environment:
  site: docs.openswitcher.org
packages:
  - sphinx
  - py3-sphinx
  - py3-sphinx_rtd_theme
tasks:
  - build: |
      cd pyatem/docs
      make html
  - deploy: |
      cd pyatem/docs/_build
      tar -C html -cvz . > site.tar.gz
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
sources:
  - https://git.sr.ht/~martijnbraam/pyatem
