image: alpine/edge
packages:
  - sphinx
  - py3-sphinx
  - py3-sphinx_rtd_theme
tasks:
  - build: |
      cd pyatem/docs
      make html
  - deploy: |
      ls -lah
sources:
  - https://git.sr.ht/~martijnbraam/pyatem
